import ZonaPage from "./ZonaTemplate";
const MudanzasSanTelmo = () => <ZonaPage
  zona="San Telmo"
  slug="san-telmo"
  descripcion="Mudanzas en San Telmo, La Boca y Constitucion. Expertos en el casco historico de Buenos Aires con edificios de epoca y calles adoquinadas."
  contenido="San Telmo es uno de los barrios mas antiguos e historicos de Buenos Aires, con edificios de principios del siglo XX, inquilinatos reconvertidos y lofts modernos. Sus calles adoquinadas y angostas son un desafio logistico que en La Mudanza resolvemos con camiones del tamano adecuado y personal experimentado. Muchos de nuestros clientes en San Telmo son artistas, diseñadores y profesionales que valoran la atencion al detalle tanto como nosotros."
  faqs={[{"q": "Como manejan las calles angostas de San Telmo?", "a": "Usamos camiones de tamano apropiado para las calles adoquinadas de San Telmo. Conocemos los accesos y sabemos como posicionar el vehiculo para minimizar el tiempo de carga."}, {"q": "Pueden mudarnos desde un loft en San Telmo?", "a": "Si, tenemos experiencia en mudanzas de lofts en San Telmo. Los lofts suelen tener escaleras industriales y espacios abiertos que requieren tecnicas especificas de traslado."}, {"q": "Trabajan en La Boca y Barracas?", "a": "Si, ademas de San Telmo cubrimos La Boca, Barracas y Constitucion. Son barrios con mucha actividad de mudanzas que atendemos regularmente."}, {"q": "Cuanto cuesta mudarse en San Telmo?", "a": "En La Mudanza no manejamos precios fijos porque cada mudanza es diferente. El costo depende del volumen, la distancia, el acceso al inmueble, si necesitas embalaje y otros factores. Por eso hacemos presupuestos cerrados y sin cargo para cada cliente. Contactanos por WhatsApp o telefono y te cotizamos sin compromiso."}]}
/>;
export default MudanzasSanTelmo;
