import ZonaPage from "./ZonaTemplate";
const MudanzasTigre = () => <ZonaPage
  zona="Tigre"
  slug="tigre"
  descripcion="Mudanzas en Tigre, Nordelta y countries del norte del GBA. Experiencia en barrios privados, countries y zonas de isla."
  contenido="Tigre es uno de los destinos mas elegidos por familias que buscan calidad de vida fuera de la ciudad. Sus countries, barrios cerrados y la zona de islas requieren experiencia especifica en logistica de acceso. En La Mudanza tenemos protocolo para entrar a countries de Nordelta, Los Alisos y todos los barrios privados del partido. Coordinamos con las administraciones con anticipacion y cumplimos todos los requisitos de seguridad para que tu mudanza sea sin inconvenientes."
  faqs={[{"q": "Pueden entrar a Nordelta y otros countries de Tigre?", "a": "Si, tenemos experiencia entrando a Nordelta y todos los countries del partido de Tigre. Gestionamos el permiso de ingreso con anticipacion y cumplimos todos los protocolos de seguridad."}, {"q": "Cuanto cuesta una mudanza desde CABA a Tigre?", "a": "En La Mudanza no manejamos precios fijos porque cada mudanza es diferente. El costo depende del volumen, la distancia, el acceso al inmueble, si necesitas embalaje y otros factores. Por eso hacemos presupuestos cerrados y sin cargo para cada cliente. Contactanos por WhatsApp o telefono y te cotizamos sin compromiso."}, {"q": "Hacen mudanzas a las islas de Tigre?", "a": "Si, tenemos experiencia en mudanzas a las islas del Delta. Coordinamos el traslado hasta el embarcadero y el transporte en lancha hasta el destino final."}, {"q": "Con cuanta anticipacion hay que reservar para Tigre?", "a": "Para mudanzas a countries de Tigre recomendamos reservar con al menos 10 dias de anticipacion para gestionar los permisos de ingreso con la administracion del barrio."}]}
/>;
export default MudanzasTigre;
